PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/63b3737b77be510029a2c3e85c5c6a56afcc1b77

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/7fffab1610d2ea08a95383febd0579e0037b6b51) in current PX4/master (31f3a21849e45ea5f110ddb6de2b09a630f54fc6)
https://github.com/PX4/NuttX/compare/7fffab1610d2ea08a95383febd0579e0037b6b51...63b3737b77be510029a2c3e85c5c6a56afcc1b77

63b3737b77 (HEAD, origin/master) CI: Add logic for determining which branches of OS App and Testing repos should be used
fe0ba38580 fs/littlefs: upgrade littlefs to v2.2.1
43ee4ae184 wireless: ieee802154: nxstyle fixes
de11caffba wireless: pktradio: nxstyle fixes
e36d93f600 wireless: bluetooth: nxstyle fixes
0a673d759d Corrected build error
e6af32c88f Run nxstyle against all files modified by PR 848
2f7e003ef8 arch/arm/src/armv7-m:  Use Apache 2.0 license
048d4954a0 crypto: nxstyle fixes
e6b47ea948 video: videomode: nxstyle cleanup

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/2aabd1c9a73992b6e6b54cefbdfb6fa1c86fe17b

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/95e105548a2037f42bf2f13b214ae083b921ff03) in current PX4/master (31f3a21849e45ea5f110ddb6de2b09a630f54fc6)
https://github.com/PX4/NuttX-apps/compare/95e105548a2037f42bf2f13b214ae083b921ff03...2aabd1c9a73992b6e6b54cefbdfb6fa1c86fe17b

2aabd1c9 (HEAD -> master, origin/master) webclient: run through nxstyle
f8f16975 webclient: use getaddrinfo to get IPv4 addresses on dual stack systems
51cbd422 Revert "build.yml: Remove -G from cibuild.sh command line"
2749e646 system: nxplayer & nxrecorder: nxstyle fixes
1697c649 examples: nxwidget: nxstyle fixes
c9eaf0be examples: i2sloop: nxstyle fixes
3cdb8107 examples: i2schar: nxstyle fixes
989988fa build.yml: Remove -G from cibuild.sh command line
f18b283e nshlib: add printf command to README.TXT
63288eb8 fix apps/include/graphics/nxwidgets/cwidgetcontrol.hxx:550:20: error: ‘m_xyinput’ was not declared in this scope